2016-01-03 22:27:00,487 [Dummy-1:3528] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-01-03 22:27:00,503 [Dummy-1:3528] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-01-03 22:36:28,858 [Dummy-1:10472] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-01-03 22:36:28,865 [Dummy-1:10472] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-01-03 22:36:32,546 [Thread-2:7348] [blog.views:16] [views:index] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2016-01-04 20:52:33,423 [Dummy-1:8540] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2016-01-04 20:52:33,437 [Dummy-1:8540] [django.db.backends:89] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2016-01-04 20:52:47,582 [Thread-2:7840] [django.template:923] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\template\base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2016-01-04 20:52:50,033 [Thread-3:200] [blog.views:25] [views:index] [ERROR]- [Errno 2] No such file or directory: 'sss.txt'
2016-01-04 20:52:50,448 [Thread-4:3164] [django.template:923] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\template\base.py", line 901, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
